### ISSUE TITLE
discovery port incorrect?

### ISSUE THREAD

**Issue by Zargonb** [StefanoTesla/ascom-alpacha-switch-dome-board#4]
Hi - I've just started using your code here for my UPS power fail signal in NINA.

In main.cpp line 77 you have port 4567 as the discovery port however it should be   (udp.listen(32227)) otherwsie it doesn't seem to work. 

thanks for the excellent code

**Comment by StefanoTesla** [comment]
Thank you so much for discovery this issue! At the beginning of version 3.0 I would like also to make the ascom alpaca ports configurable, but one time I prepare all the structure I found that I needed to change all the software configuration, so i went back but I make a mistake, the port 4567 it the alpaca device's port!
I didn't see the problem cause I didn't retry the discovery function.

Feel free to close the issue

**Comment by Zargonb** [comment]
thanks
